version: '3.9'

volumes:
  pgdata:
  static_volume:

services:

  postgredb:
    image: postgres:latest
    environment:
      POSTGRES_DB: "netology_stocks_products"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Tehn89tehn"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d netology_stocks_products"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    volumes:
      - .:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
      - ./logs:/var/log

  python_service:
    build: .
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input --clear && gunicorn stocks_products.wsgi -b 0.0.0.0:8000"
    volumes:
      - static_volume:/src/static
    environment:
      - MY_ENV=stocks_products
    expose:
      - 8000
    depends_on:
      - postgredb

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/src/static
    ports:
      - 80:80
    depends_on:
      - python_service