version: '3.9'

volumes:
  pgdata:

services:

  postgredb:
    image: postgres:latest
    environment:
      POSTGRES_DB: "netology_stocks_products"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Tehn89tehn"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d netology_stocks_products"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    volumes:
      - .:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
      - ./logs:/var/log

  python_service:
    build: .
    environment:
      - MY_ENV=stocks_products
    ports:
      - "8000:8000"
    depends_on:
      - postgredb

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "9000:8978"